version: '3.8'

services:
  server:
    build: .
    container_name: mpt_server
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=mpt_service_db
      - POSTGRES_USER=mpt_service_user
      - POSTGRES_PASSWORD=mpt_service_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - SECRET_KEY=your-secret-key-here
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:18.2-alpine3.23
    container_name: mpt_postgres
    environment:
      POSTGRES_DB: mpt_service_db
      POSTGRES_USER: mpt_service_user
      POSTGRES_PASSWORD: mpt_service_password
      PGDATA: /var/lib/postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    restart: unless-stopped
volumes:
  postgres_data:
